"""empty message

Revision ID: 86ccf1c72ba1
Revises: ca8d13305c21
Create Date: 2020-11-11 14:34:13.878405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86ccf1c72ba1'
down_revision = 'ca8d13305c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.add_column('user', sa.Column('income', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'income')
    op.drop_table('expense')
    # ### end Alembic commands ###
